security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_CLIENT
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern:    ^/api
            stateless:  true
            anonymous:  false
            provider:   fos_userbundle
            api_key:    true

        secured_client_area:
            pattern: ^/
            anonymous: ~
            provider: fos_userbundle
            form_login_captcha:
                check_path: /login_check
                login_path: /login
                always_use_default_target_path: false
                default_target_path: app_admin_dashboard_list
                success_handler:     app_user.login_success_handler
            logout:
                path:   /logout
                target: /login

    access_control:
        - { path: ^/api, roles: ROLE_ADMIN }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/return/paypal$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/invoice/show, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/invoice/pay, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/order, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_CLIENT }